### ISSUE TITLE
Mobile view port

### ISSUE THREAD

**Issue by Claraviolet** [DD-GitH/emerald-theme-mybb#1]
I don't think you have set the mobile view port for this theme Amaz. For the time being, I have set emerald theme as the default theme for my site. If you visit, http://animemangaforum.com/  using a phone, you will be able to notice that it's not responsive as of now.  

Thanks and Regards,
Claraviolet.

**Comment by DD-GitH** [comment]
Hi,
It depends on navigators, i use Firefox and responsivity is okay for me. Next version will include more compatibility

**Comment by Claraviolet** [comment]
Well, I have tried chrome, samsung browser and the alignment isn't good. I will try with firefox now. I hope you consider as many users are using it.
