### ISSUE TITLE
Change title logo ?

### ISSUE THREAD

**Issue by eeradptin** [DD-GitH/emerald-theme-mybb#10]
Please tell me how to change the diamond logo at the top.
My forum entrepreneurera.in/forum

**Comment by doh4ckl1f3** [comment]
Im top

12 Eki 2017 14:04 tarihinde "eeradptin" <notifications@github.com> yazdı:

**Comment by dvddvd300** [comment]
In header
(line 2)

`<a href="{$mybb->settings['bburl']}" id="logo"><i class="fa fa-diamond"></i> (forum name)</a>`

**Comment by eeradptin** [comment]
yeah got the header line 2 now what to do to remove the logo diamond shape?

**Comment by dvddvd300** [comment]
Remove `<i class="fa fa-diamond"></i>`
