### ISSUE TITLE
From where i can change the announcement ?

### ISSUE THREAD

**Issue by eeradptin** [DD-GitH/emerald-theme-mybb#11]
I want to change "This is an example !" shown in the announcement. Please help
My forum https://entrepreneurera.in/forum/

**Comment by miyagiman** [comment]
Hey how did you change it?
Also, how did you change these parts?
http://puu.sh/xYu7F/df195e2156.png 
Thanks in advanced

**Comment by dvddvd300** [comment]
I recommend you see this document:
http://dvd.esy.es/foro/uploads/documentationemerald.html

**Comment by DD-GitH** [comment]
Documentation is there. Thanks
