### ISSUE TITLE
Features description grammatical error

### ISSUE THREAD

**Issue by hash-cloud-dev** [DD-GitH/emerald-theme-mybb#12]
Hello, please visit: https://community.mybb.com/mods.php?action=view&pid=1037

The description of "Features" on the theme page @ mybb.com has an embarrassing spelling mistake (It happens to the best of us!).

> Features :
> Clean & Modern
> Responsivie & Retina Ready ... **change to** ... Responsive & Retina Ready

See above. Change the spelling on responsive to Responsive, not Responsivie.

...

Also, are you hiring? If so, how may I inquire?

**Comment by DD-GitH** [comment]
Hi, sorry for the very late answer, i usually see the thread on MyBB and forget Github.
Thanks for the report.
I'm ready for freelance. Just email me at business@developement.design
