### ISSUE TITLE
Text alignment Issue for Mobile version (Android)

### ISSUE THREAD

**Issue by nickhanson232** [DD-GitH/emerald-theme-mybb#14]
Hello,

Would like to inform you that while I'm looking at a thread via showthread.php on a mobile device (I notice it on my OnePlus One, Android), the text gets cut out and it's not formatted well. Part of it is cut out. I can't move it on screen as well.

![screenshot_20171015-223928 857](https://user-images.githubusercontent.com/32828069/31594332-e3df039a-b1f9-11e7-8d8c-a9e388b3f6d6.png)

**Comment by dvddvd300** [comment]
also happens to me on the register form

**Comment by DD-GitH** [comment]
This was fixed today. Greets

**Comment by sscs1** [comment]
I already have Emerald and I'm trying to import the latest XML via  ACP>Templates & Style>Import a Theme but I'm just getting the error "MyBB could not find the theme with the file you uploaded. Please check the file is the correct and is not corrupt."
