### ISSUE TITLE
How to edit the announcement section?

### ISSUE THREAD

**Issue by dneff613** [DD-GitH/emerald-theme-mybb#2]
Love the theme. How do you edit the announcement section of the theme?

**Comment by dneff613** [comment]
Got that figured out! New question: The threads won't link to a user profile. Why is that? Here's a screen shot:

When I click on the user "GameMod" it does not go to that users profile.

<img width="1280" alt="screenshot 2017-09-17 19 01 23" src="https://user-images.githubusercontent.com/24865496/30525742-a1d75d60-9bda-11e7-8dc2-fb8151f735a2.png">

**Comment by Free-VPS** [comment]
How to Edit Announcement 
Go to Admin Panel
Click Templates & Style
then click Templates and choose "Emerald Templates"
Click Index page Template and choose  index
Find  " It is an example"
and edit

**Comment by dneff613** [comment]
Thanks! Do you know why the profile links don't work?

**Comment by Free-VPS** [comment]
no

**Comment by DD-GitH** [comment]
Hi, it'll be corrected in v1.2 that'll get out soon

**Comment by DD-GitH** [comment]
This is corrected on v1.2 (now available)
Issue closed.
