### ISSUE TITLE
Problem upgrading to XML 1.4

### ISSUE THREAD

**Issue by sscs1** [DD-GitH/emerald-theme-mybb#21]
Hi.  I'm trying to upgrade to the latest XML 1.4 via ACP>Templates & Style>Import a Theme but I'm just getting the error "MyBB could not find the theme with the file you uploaded. Please check the file is correct and is not corrupt." Am I doing something wrong? Thanks.

**Comment by sscs1** [comment]
Now tried various methods.  I wonder if anyone has actually managed to import version 1.4? Or maybe there's a bug.

**Comment by DD-GitH** [comment]
Hello, try with the new v1.5 it should work. Otherwise, download via MyBB mods site
Greets
