### ISSUE TITLE
'Online'/'Offline' Colours

### ISSUE THREAD

**Issue by zackwwww** [DD-GitH/emerald-theme-mybb#25]
I've installed Emerald and made a few styling changes, it's looking and working really nicely so thanks a lot for that - just one small issue I'm having.

I've gone into the Emerald global.css and changed the text colour in .offline and .online but on the forum those bits of text still show up as the default red and green. Have cleared cache and refreshed the global css to check that my changes saved, so not sure what the issue could be..

Here's what I'm referring to:
https://i.imgur.com/xIWBGT6.png

**Comment by DD-GitH** [comment]
Hello, search in the postbit templates you'll find the code for Online/Offline
Example : postbit_offline template you'll find <span style="color:red;"> 
Greets !
