### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Ecliips3** [DD-GitH/emerald-theme-mybb#27]
Hello
I can't just fixed footer on bottom of the page when i scroll up the footer follow the "content" div
code : 
`.footer-distributed {
position: absolute;
bottom: 0;
}
body {
position: relative
}`
Thank you for your time

My site 
[https://forum.kronolia.fr/](url)

**Comment by DD-GitH** [comment]
Bonjour,
S'il vous plait, mettez le thème Emerald en tant que thème par défaut pour le forum pour que je puisse voir le problème.

Merci de votre compréhension
