### ISSUE TITLE
Google Fonts are not loaded over https

### ISSUE THREAD

**Issue by callumthomson** [DD-GitH/emerald-theme-mybb#3]
On https enabled sites, fonts not loaded over https are blocked. These fonts will not work.

You need to use https instead of http when loading fonts from google

**Comment by DD-GitH** [comment]
This is actually corrected in V1.1 that'll be released very soon. Thanks for your patience

**Comment by DD-GitH** [comment]
This is corrected on v1.2 (now available)
Issue closed.
