### ISSUE TITLE
Thread content jumps to the left

### ISSUE THREAD

**Issue by bmwf2x** [DD-GitH/emerald-theme-mybb#4]
Hi,

When the thread content goes by the user details, the table jumps to the left. I find it hard to explain in english, please take a look at the screenshot.

Is there a way to fix this? I like the content to be in one straight line. 

![schermafbeelding 2017-09-26 om 14 39 21](https://user-images.githubusercontent.com/32299550/30860769-96d1647a-a2c8-11e7-8580-735b1da90432.png)

**Comment by DD-GitH** [comment]
Hi, we've already got this message from another user. This will be corrected on v1.1 (release very soon)

**Comment by DD-GitH** [comment]
This is corrected on v1.2 (now available)
Issue closed.
