### ISSUE TITLE
 possibility to add "OUGC Custom Language" for theme translations

### ISSUE THREAD

**Issue by dvddvd300** [DD-GitH/emerald-theme-mybb#41]
possibility to add "_OUGC Custom Language_" plugin for theme translations.
 _(It is a possibility, what do you think?)_

**Comment by iagovar** [comment]
Not really necessary.

**Comment by DD-GitH** [comment]
Hello,
Support and other stuffs about the theme are not anymore discussed on github (from this week).
If you have anything to post, please go to the new forum : https://developement.design/forum/forumdisplay.php?fid=12

Best Regards,
AmazOuz
