### ISSUE TITLE
{showeditorplaceholder} in control planel

### ISSUE THREAD

**Issue by iagovar** [DD-GitH/emerald-theme-mybb#42]
Hi, in the control planel there is a place where it's shown like this: https://i.imgur.com/yt58rnr.png

{showeditorplaceholder} should place some options that are not displaying.

**Comment by dvddvd300** [comment]
hello, it's in the ACP (Admin Control Panel), MCP (moderator Control Panel) or UCP (user Control Panel)?

**Comment by iagovar** [comment]
UCP

**Comment by DD-GitH** [comment]
Hello,
Support and other stuffs about the theme are not anymore discussed on github (from this week).
If you have anything to post, please go to the new forum : https://developement.design/forum/forumdisplay.php?fid=12

Best Regards,
AmazOuz
