### ISSUE TITLE
Selecting emerald as theme deactivates some options in the UCP

### ISSUE THREAD

**Issue by iagovar** [DD-GitH/emerald-theme-mybb#43]
When selecting Emerald as theme for the forum, the following options are deactivated in the UCP. I'm trying this with a fresh installation.

- Display images in posts.
- Display videos in posts.

- Show the MyCode formatting options on the posting pages

**Comment by DD-GitH** [comment]
Hello,
Support and other stuffs about the theme are not anymore discussed on github (from this week).
If you have anything to post, please go to the new forum : https://developement.design/forum/forumdisplay.php?fid=12

Best Regards,
AmazOuz
