### ISSUE TITLE
Issue with moderation

### ISSUE THREAD

**Issue by Falkio** [DD-GitH/emerald-theme-mybb#6]
Hello,
When i try to delte or moove or other a thread that write nothing selected but i have select a thread to moderate :/

**Comment by DD-GitH** [comment]
Templates & Style -> Emerald template -> Ungrouped templates -> headerinclude -> after "var cookiePrefix ..." add this: 

var cookieSecureFlag = "{$mybb->settings['cookiesecureflag']}";

**Comment by pierrepinon** [comment]
I create a PR for this with your code @DD-GitH
